### ISSUE TITLE
use of Flatten Matrix

### ISSUE THREAD

**Issue by nileio** [sammachin/node-red-contrib-google-sheets#8]
Hi @sammachin 
thanks for the node.
What is the use of the Flatten Matrix feature please? On what context can it be used ?
Also are you considering to add getByDataFilter or updateByDataFilter APIs? Those will be great addition to conditionally get or update values based on custom conditions or formulas.

**Comment by novitibo** [comment]
yp, what is Flatten Matrix feature?

**Comment by sammachin** [comment]
There's a bit of history to this you can see from this issue https://github.com/sammachin/node-red-contrib-google-sheets/issues/3

If you fetch multiple rows and columns you end up with a 'matrix' that is an array of arrays, or even if you fetch a single column you end up with an array of single value arrays, In the first version of the node I auto flattened this into one array but some people wanted to keep the matrix structure in tact so its now an option. The easiest way to see it is to fetch a colum like A1:A5, without flatten enabled you will get back [[A1],[A2],[A3],[A4],[A5]] instead of [A1,A2,A3,A4,A5]

@nileio Regarding the other 2 API calls I've not looked at that but we could consider that, have you got a link to the API ref?

**Comment by nileio** [comment]
@sammachin thanks it makes sense
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/getByDataFilter
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchUpdateByDataFilter

I checked the docs. It is a bit tricky to get the datafilter easily configurable in a node though.. It wasn't straight forward but worth checking.
